### ISSUE TITLE
Pickle import on python 3.5 not working

### ISSUE THREAD

**Issue by henriquefacioli** [jaysonsantos/django-uwsgi-mail#5]
Hello!
I've been trying to run this package with python 3.5 and when trying to send an email i get: 
```
<class 'ImportError'>
No module named 'Pickle'
```
I believe it could be fixed if changed Pickle for pickle it would work as seen in this post ([stackoverflow](https://stackoverflow.com/questions/37132899/installing-cpickle-with-python-3-5))

I don't know if you intend to make it work on 3.x but i believe to do so, all it takes is changing Pickle to pickle

**Comment by jaysonsantos** [comment]
Hey @henriquefacioli I am actually not maintaining this but if you are willing to send a patch I would accept it for sure.

**Comment by jaysonsantos** [comment]
Fixed in #7
